## Chapter 3
### Deep learning from scratch



In [1]:
import numpy as np
from numpy import ndarray
from typing import Callable, Dict, Tuple, List


### Operations
Operations represent the constituent functions in our neural networks. The book creates classes for these, I'm going to prefer a more functional approach.

Some characteristics of these operations (pp. 73-74):
* Forward and backward passes
* Receive an input `ndarray` and return an output `ndarray`
* Some operations will have parameters
* Each operation will send outputs forward on the forward pass and will receive an "output gradient" on the backward pass (the partial derivative of the loss with respect to every element of the operation's output
* On the backward pass, each operation will send an "input gradient" backward (the partial derivative of the loss with respect to each element of the input)


In [5]:
def operation(input: ndarray) -> ndarray:
    return "Not implemented"

def weight_multiply(input: ndarray,
                    weights: ndarray) -> ndarray:
    return np.dot(input, weights)

def bias_add(input: ndarray,
             bias: ndarray) -> ndarray:
    return input + bias

def init_weights(neurons: int):
    '''
    Initialize weights on first forward pass of model.
    '''
    W = np.random.randn(neurons, neurons)
    B = np.random.randn(1, neurons)
    return W, B

def calc_input_grad(input):
    
    return input_grad

## Initializing stuff?
INPUT = np.array([[1,2,3]])
NEURONS = INPUT.shape[1]
WEIGHTS = np.random.randn(NEURONS, NEURONS)
BIAS = np.random.randn(1, NEURONS)


bias_add(INPUT, BIAS)

array([[0.79751774, 1.15886005, 3.15504754]])

### Layers
Layers are a series of linear operations followed by a nonlinear operation.

Series of operations in a typical layer:
1. Multiply by weights
2. Add bias term
3. Activation function

In [13]:
from src.math import sigmoid

def layer(input: ndarray,
         activation) -> ndarray:
    NEURONS = input.shape[1]
    WEIGHTS, BIAS = init_weights(NEURONS)
    output = weight_multiply(input, WEIGHTS)
    output = bias_add(output, BIAS)
    output = activation(output)
    return output

layer(input = INPUT, activation = sigmoid)

array([[0.150547  , 0.90437885, 0.45497504]])

In [4]:
np.random.randn(1, 13)

array([[-1.07875307, -1.18399713, -0.79782866,  0.24458374,  0.95062162,
        -1.16922789, -0.20656699,  0.76551   ,  0.04524374,  1.53495616,
        -0.68553201,  0.22923805, -2.243146  ]])